baseURL = "https://hugo-task-management.netlify.app/"
languageCode = "en-us"
title = "Hugo task management platform"
theme = "dashboard"

[params]
  dashboardColumns = ["TODO", "Blocked", "Progress", "Review", "Done"]
  defaultStatus = "TODO"
  defaultTeam = ""
  defaultProject = "Hugo Task Management"
  paramsInTaskDetail = ["status", "date", "project", "team", "assignedTo", "tags", "completedAt"]
