baseURL = "https://hugo-task-management.netlify.app/"
languageCode = "en-us"
title = "Hugo task management platform"
theme = "dashboard"

[params]
  dashboardColumns = ["TODO", "Blocked", "In progress", "In Review", "Done"]