baseURL = "https://hugo-task-management.netlify.app/"
languageCode = "en-us"
title = "Hugo task management platform"
theme = "dashboard"

[taxonomies]
  project = "projects"
  tag = "tags"
  user = "users"
  team = "teams"

[params]
  dashboardColumns = ["TODO", "Blocked", "Progress", "Review", "Done"]
  paramsInTaskDetail = ["status", "date", "projects", "teams", "users", "tags", "completedAt"]
  defaultStatus = "TODO"
  defaultTeams = []
  defaultUsers = ["aquilax"]
  defaultProjects = ["Hugo Task Management"]
  defaultTags = []
